# Generated by Django 4.2.23 on 2025-06-16 08:54

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tag_article_cover_image_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='author_photo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(default='Журналіст', max_length=130),
            preserve_default=False,
        ),
    ]
