# Generated by Django 4.2.23 on 2025-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_author_photo_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('news', 'news'), ('column', 'column'), ('interview', 'interview')], default='news', max_length=20),
            preserve_default=False,
        ),
    ]
