# Generated by Django 4.2.23 on 2025-06-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='role_en',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='role_uk',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uk',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
