# Generated by Django 4.2.23 on 2025-07-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_article_text_en_article_text_uk_article_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('news', 'news'), ('column', 'column'), ('interview', 'interview')], max_length=20, verbose_name='Article type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[1500, 1000], upload_to='cover_image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='author_photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.CharField(max_length=130, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='author',
            name='role_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='author',
            name='role_uk',
            field=models.CharField(max_length=130, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_uk',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Name'),
        ),
    ]
